name: elmohandes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  meta: ^1.15.0
  path: ^1.9.1
  pdf: ^3.11.3
  pretty_dio_logger: ^1.4.0
  printing: ^5.14.2
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  lints: ^5.1.1
  retrofit_generator: ^9.1.9

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
      - asset: assets/fonts/Cairo-Black.ttf
        weight: 900
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 400
      - asset: assets/fonts/Cairo-Light.ttf
        weight: 300
      - asset: assets/fonts/Cairo-ExtraLight.ttf
        weight: 200
    - family: ArefRuqaa
      fonts:
      - asset: assets/fonts/ArefRuqaa-Bold.ttf
        weight: 700
      - asset: assets/fonts/ArefRuqaa-Regular.ttf
        weight: 400

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.jpg
  android_12:
    image: assets/images/icon.jpg
    icon_background_color: "#ffffff"
  fullscreen: true

# إعدادات Launcher Icons
flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256 # حجم الأيقونة للويندوز
  image_path: "assets/icons/app_icon.png" # تأكد من وجود الصورة هنا
  adaptive_icon_background: "#ffffff" # لون الخلفية لأيقونة أندرويد المتكيفة
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png" # صورة أيقونة متكيفة للأندرويد
  min_sdk_android: 21
